# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildarmv7:
    name: AltEngine-debug
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: zulu
          java-version: 12

      - name: Setup Android SDK
        uses: android-actions/setup-android@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install flixel 4.11.0 --quiet
          haxelib run lime setup flixel
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui 2.4.0 --quiet
          haxelib install flixel-addons 2.11.0 --quiet
          haxelib install polymod --quiet
          haxelib install spinehaxe --quiet
          haxelib git polymod-mastereric https://github.com/MasterEric/polymod --quiet
          haxelib install hscript --quiet
          haxelib git hscript-yoshiengine https://github.com/YoshiCrafter29/hscript-improved --quiet
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex --quiet
          haxelib git hxCodec https://github.com/polybiusproxy/hxcodec --quiet
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit --quiet
          haxelib git SScript https://github.com/TheWorldMachinima/SScript --quiet
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib list
      - name: Setup Lime
        run: |
          echo "${{github.run_id}}" > VERSION
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: |
         haxelib run lime build android -D no-compilation -D luajit_static -D macro-times -D analyzer-optimize -armv7 --app-version="4.0.0-${{ github.run_id}}"
         cd export/release/android/bin/app/build/outputs/apk/debug
         mv AltEngine-debug.apk AltEngine-debug.apk

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: AltEngine-debug
          path: export/release/android/bin/app/build/outputs/apk/debug
  buildarm64:
    name: Alt Engine Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout...
        uses: actions/checkout@main

      - name: Setup Android NDK...
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK...
        uses: actions/setup-java@main
        with:
          distribution: zulu
          java-version: 12

      - name: Setup Android SDK...
        uses: android-actions/setup-android@main

      - name: Setup Haxe...
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib...
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install flixel 4.11.0 --quiet
          haxelib run lime setup flixel
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui 2.4.0 --quiet
          haxelib install flixel-addons 2.11.0 --quiet
          haxelib install polymod --quiet
          haxelib install spinehaxe --quiet
          haxelib git polymod-mastereric https://github.com/MasterEric/polymod --quiet
          haxelib install hscript --quiet
          haxelib git hscript-yoshiengine https://github.com/YoshiCrafter29/hscript-improved --quiet
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex --quiet
          haxelib git hxCodec https://github.com/polybiusproxy/hxcodec --quiet
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit --quiet
          haxelib git SScript https://github.com/TheWorldMachinima/SScript --quiet
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib list
      - name: Setup Lime...
        run: |
          echo "${{github.run_id}}" > VERSION
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Building...
        run: |
         haxelib run lime build android -D no-compilation -D luajit_static -D macro-times -D analyzer-optimize -arm64 --app-version="4.0.0-${{ github.run_id}}"
         cd export/release/android/bin/app/build/outputs/apk/debug
         mv AltEngine-debug.apk AltEngine Release.apk

      - name: Publish Artifact...
        uses: actions/upload-artifact@main
        with:
          name: AltEngine-release
          path: export/release/android/bin/app/build/outputs/apk/debug
